spring:
  application:
    name: patrol_be
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      file-size-threshold: 2MB

server:
  address: 0.0.0.0
  port: 9299

#  ssl:
#    enabled: true
#    key-store: file:/C:/Users/viet.ta/keystore.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: patrol-ssl